SELECT DISTINCT PAPF.PERSON_NUMBER "PersonNumber"
	, PAAM.EFFECTIVE_LATEST_CHANGE "EffectiveLatestChange"
	, PAAM.EFFECTIVE_SEQUENCE "EffectiveSequence"
	, HOUFT_BU.NAME "BusinessUnitShortCode"
	, TO_CHAR(PAAM.EFFECTIVE_END_DATE, 'YYYY/MM/DD') "EffectiveEndDate"
	, TO_CHAR(PAAM.EFFECTIVE_START_DATE, 'YYYY/MM/DD') "EffectiveStartDate"
	, PAAM.ACTION_CODE "ActionCode"
	, nvl(CASE WHEN PAAM.WORK_TERMS_ASSIGNMENT_ID IS NOT NULL				THEN (SELECT DISTINCT PAAM_WT.ASSIGNMENT_NUMBER
							FROM PER_ALL_ASSIGNMENTS_M PAAM_WT
							WHERE 1 = 1
								AND PAAM_WT.ASSIGNMENT_ID = PAAM.WORK_TERMS_ASSIGNMENT_ID
								AND SYSDATE BETWEEN PAAM_WT.EFFECTIVE_START_DATE AND PAAM_WT.EFFECTIVE_END_DATE)
					ELSE NULL
				END, '') "WorkTermsNumber"
	, PAAM.ASSIGNMENT_TYPE "AssignmentType"
	, PAAM.ASSIGNMENT_STATUS_TYPE "AssignmentStatusTypeCode"
	, HIKM.SOURCE_SYSTEM_ID "SourceSystemId"
	, HIKM.SOURCE_SYSTEM_OWNER "SourceSystemOwner"
	, PAAM.ASSIGNMENT_NUMBER "AssignmentNumber"
	, PAAM.ASSIGNMENT_NAME "AssignmentName"
	, nvl (CASE WHEN PAAM.POSITION_ID IS NOT NULL
					THEN (SELECT DISTINCT HAPF.POSITION_CODE
							FROM HR_ALL_POSITIONS_F HAPF
							WHERE 1 = 1
								AND HAPF.POSITION_ID = PAAM.POSITION_ID
								AND SYSDATE BETWEEN HAPF.EFFECTIVE_START_DATE AND HAPF.EFFECTIVE_END_DATE)
					ELSE ''
				END, '') "PositionCode"
	, nvl (CASE WHEN PAAM.ORGANIZATION_ID IS NOT NULL
					THEN (SELECT DISTINCT HOUFT.NAME
							FROM HR_ORGANIZATION_UNITS_F_TL HOUFT
								, HR_ORG_UNIT_CLASSIFICATIONS_F HOUCF
							WHERE 1 = 1
								AND HOUFT.ORGANIZATION_ID = PAAM.ORGANIZATION_ID
								AND PAAM.ORGANIZATION_ID = HOUCF.ORGANIZATION_ID
								AND HOUCF.CLASSIFICATION_CODE = 'DEPARTMENT'
								AND SYSDATE BETWEEN HOUFT.EFFECTIVE_START_DATE AND HOUFT.EFFECTIVE_END_DATE
								AND SYSDATE BETWEEN HOUCF.EFFECTIVE_START_DATE AND HOUCF.EFFECTIVE_END_DATE)
					ELSE ''
				END, '') "DepartmentName"
	, nvl (CASE WHEN PAAM.GRADE_ID IS NOT NULL
					THEN (SELECT DISTINCT PGF.GRADE_CODE
							FROM PER_GRADES_F PGF
							WHERE 1 = 1
								AND PAAM.GRADE_ID = PGF.GRADE_ID
								AND SYSDATE BETWEEN PGF.EFFECTIVE_START_DATE AND PGF.EFFECTIVE_END_DATE)
					ELSE ''
				END, '') "GradeCode"
	, PAAM.FREQUENCY "Frequency"
	, PAAM.FULL_PART_TIME "FullPartTime"
	, PAAM.LABOUR_UNION_MEMBER_FLAG "LabourUnionMemberFlag"
	, PAAM.MANAGER_FLAG "ManagerFlag"
	, PAAM.NORMAL_HOURS "NormalHours"
	, PAAM.PERMANENT_TEMPORARY_FLAG "PermanentTemporary"
	, nvl (CASE WHEN PAAM.LOCATION_ID IS NOT NULL
					THEN (SELECT DISTINCT PL.INTERNAL_LOCATION_CODE
							FROM PER_LOCATIONS PL
							WHERE 1 = 1
								AND PAAM.LOCATION_ID = PL.LOCATION_ID)
					ELSE ''
				END, '') "LocationCode"
	, nvl (CASE WHEN PAAM.JOB_ID IS NOT NULL
					THEN (SELECT DISTINCT PJF.JOB_CODE
							FROM PER_JOBS_F PJF
							WHERE 1 = 1
								AND PAAM.JOB_ID = PJF.JOB_ID
								AND SYSDATE BETWEEN PJF.EFFECTIVE_START_DATE AND PJF.EFFECTIVE_END_DATE)
					ELSE ''
				END, '') "JobCode"
FROM PER_ALL_ASSIGNMENTS_M PAAM
	, PER_ALL_PEOPLE_F PAPF
	, PER_PERIODS_OF_SERVICE PPOS
	, HR_ORGANIZATION_UNITS_F_TL HOUFT_LE
	, HR_ORG_UNIT_CLASSIFICATIONS_F HOUCF_LE
	, HRC_INTEGRATION_KEY_MAP HIKM
	, HR_ORGANIZATION_UNITS_F_TL HOUFT_BU
	, HR_ORG_UNIT_CLASSIFICATIONS_F HOUCF_BU
WHERE 1 = 1
	AND HOUFT_BU.ORGANIZATION_ID = PAAM.BUSINESS_UNIT_ID
	AND HOUCF_BU.ORGANIZATION_ID = PAAM.BUSINESS_UNIT_ID
	AND HOUCF_BU.CLASSIFICATION_CODE = 'FUN_BUSINESS_UNIT'
	AND PAAM.PERSON_ID = PAPF.PERSON_ID
	AND HIKM.SURROGATE_ID = PAAM.ASSIGNMENT_ID
	AND PAAM.ASSIGNMENT_TYPE NOT LIKE '%T%'
	AND PAAM.EFFECTIVE_START_DATE = (SELECT MAX(PAAM2.EFFECTIVE_START_DATE)
										FROM PER_ALL_ASSIGNMENTS_M PAAM2
										WHERE 1 = 1
											AND PAAM2.PERSON_ID = PAAM.PERSON_ID)
	AND PAAM.EFFECTIVE_LATEST_CHANGE = 'Y'
	AND PPOS.PERSON_ID = PAPF.PERSON_ID
	AND PPOS.LEGAL_ENTITY_ID = HOUFT_LE.ORGANIZATION_ID
	AND HOUFT_LE.ORGANIZATION_ID = HOUCF_LE.ORGANIZATION_ID
	AND SYSDATE BETWEEN HOUFT_LE.EFFECTIVE_START_DATE AND HOUFT_LE.EFFECTIVE_END_DATE
	AND SYSDATE BETWEEN HOUCF_LE.EFFECTIVE_START_DATE AND HOUCF_LE.EFFECTIVE_END_DATE
	AND SYSDATE BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE
	AND HIKM.OBJECT_NAME = 'Assignment'
	AND PPOS.DATE_START = (SELECT MAX(PPOS2.DATE_START)
									FROM PER_PERIODS_OF_SERVICE PPOS2
									WHERE 1 = 1
									AND PPOS.PERSON_ID = PPOS2.PERSON_ID)
	AND PAPF.PERSON_NUMBER LIKE 'TEST%'
	AND HIKM.SOURCE_SYSTEM_OWNER = 'PEOPLESOFT'
	AND HOUFT_BU.NAME NOT LIKE 'DB Regio - Schiene'
ORDER BY 1
