SELECT DISTINCT PAPF.PERSON_NUMBER "PersonNumber"
	, TO_CHAR(PPNF.EFFECTIVE_START_DATE, 'YYYY/MM/DD') "EffectiveStartDate"
	, PPNF.LEGISLATION_CODE "LegislationCode"
	, PPNF.NAME_TYPE "NameType"
	, PPNF.FIRST_NAME "FirstName"
	, PPNF.LAST_NAME "LastName"
	, TO_CHAR(PPNF.EFFECTIVE_END_DATE, 'YYYY/MM/DD') "EffectiveEndDate"
	, HIKM.SOURCE_SYSTEM_OWNER "SourceSystemOwner"
	, HIKM.SOURCE_SYSTEM_ID "SourceSystemId"
FROM PER_PERSON_NAMES_F PPNF
	, PER_ALL_PEOPLE_F PAPF
	, HRC_INTEGRATION_KEY_MAP HIKM
WHERE 1 = 1
	AND PPNF.PERSON_ID = PAPF.PERSON_ID
	AND PPNF.PERSON_NAME_ID = HIKM.SURROGATE_ID
	AND PPNF.NAME_TYPE <> PPNF.LEGISLATION_CODE
	AND SYSDATE BETWEEN PPNF.EFFECTIVE_START_DATE AND PPNF.EFFECTIVE_END_DATE
	AND SYSDATE BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE
	AND HIKM.OBJECT_NAME = 'PersonName'
	AND PAPF.PERSON_NUMBER LIKE 'TEST%'
	AND HIKM.SOURCE_SYSTEM_ID NOT LIKE 'CON%'
ORDER BY 1
