SELECT DISTINCT TO_CHAR(PU.USER_ID) "UserId" 
	, PAPF.PERSON_NUMBER "PersonNumber"
	, PU.USERNAME "UserName"
	, PU.CREDENTIALS_EMAIL_SENT "CredentialsEmailSent"
	, PU.SUSPENDED "Suspended"
	, PRD.ROLE_COMMON_NAME "RoleCommonName"
	, PU.CREATED_BY "CreatedBy"
	, TO_CHAR(PU.CREATION_DATE, 'YYYY/MM/DD') "CreationDate"
	, PU.LAST_UPDATED_BY "LastUpdatedBy"
	, TO_CHAR(PU.LAST_UPDATE_DATE, 'YYYY/MM/DD') "LastUpdateDate"
	, HIKM.SOURCE_SYSTEM_ID "SourceSystemId"
	, HIKM.SOURCE_SYSTEM_OWNER "SourceSystemOwner"
FROM PER_USERS PU
	, PER_USER_ROLES PUR
	, PER_ROLES_DN PRD
	, PER_ALL_PEOPLE_F PAPF
	, HRC_INTEGRATION_KEY_MAP HIKM
WHERE 1 = 1
	AND PU.PERSON_ID = PAPF.PERSON_ID
	AND PU.USER_ID = PUR.USER_ID
	AND PUR.ROLE_ID = PRD.ROLE_ID
	AND PU.USER_ID = HIKM.SURROGATE_ID
	AND HIKM.OBJECT_NAME = 'User'
	--AND PU.USERNAME IN ('Daniel-TEST.Röder', 'User_Kenn_Test', 'User_Kenn_Test2', 'User_Kenn_Test3')
	AND PAPF.PERSON_NUMBER IN ('PTEST4001', 'PTEST4004', 'PTEST4002')
