SELECT DISTINCT PAPF.PERSON_NUMBER "PersonNumber"
	, '' "EnterpriseSeniorityDate"
	, TO_CHAR(PPOS.DATE_START, 'YYYY/MM/DD') "DateStart"
	, nvl (CASE WHEN PPOS.ACTION_OCCURRENCE_ID IS NOT NULL
					THEN (SELECT DISTINCT PAB.ACTION_CODE
							FROM PER_ACTION_OCCURRENCES PAO
								, PER_ACTIONS_B PAB
							WHERE 1 = 1
								AND PAO.ACTION_OCCURRENCE_ID = PPOS.ACTION_OCCURRENCE_ID
								AND PAB.ACTION_ID = PAO.ACTION_ID
								AND PAB.ACTION_CODE = 'HIRE')
					ELSE ''
				END, '') "ActionCode"
	, PPOS.PRIMARY_FLAG "PrimaryFlag"
	, HIKM_PAPF.SOURCE_SYSTEM_ID "SourceSystemId"
	, nvl (CASE WHEN PPOS.LEGAL_ENTITY_ID IS NOT NULL
					THEN (SELECT DISTINCT HOUFT.NAME
							FROM HR_ORGANIZATION_UNITS_F_TL HOUFT
								, HR_ORG_UNIT_CLASSIFICATIONS_F HOUCF
							WHERE 1 = 1
								AND HOUFT.ORGANIZATION_ID = PPOS.LEGAL_ENTITY_ID
								AND HOUCF.ORGANIZATION_ID = PPOS.LEGAL_ENTITY_ID
								AND HOUCF.CLASSIFICATION_CODE = 'HCM_LEMP'
								AND SYSDATE BETWEEN HOUFT.EFFECTIVE_START_DATE AND HOUFT.EFFECTIVE_END_DATE
								AND SYSDATE BETWEEN HOUCF.EFFECTIVE_START_DATE AND HOUCF.EFFECTIVE_END_DATE)
					ELSE ''
				END, '') "LegalEmployerName"
	, PPOS.PERIOD_TYPE "WorkerType"
	, PPOS.REHIRE_RECOMMENDATION "RehireRecommendationFlag"
FROM PER_PERIODS_OF_SERVICE PPOS
	, PER_ALL_PEOPLE_F PAPF
	, HRC_INTEGRATION_KEY_MAP HIKM
	, HRC_INTEGRATION_KEY_MAP HIKM_PAPF
	, PER_ALL_ASSIGNMENTS_M PAAM
WHERE 1 = 1
	AND PPOS.PERSON_ID = PAPF.PERSON_ID
	AND PPOS.PERSON_ID = PAAM.PERSON_ID
	AND PPOS.PERIOD_OF_SERVICE_ID = HIKM.SURROGATE_ID
	AND HIKM_PAPF.SURROGATE_ID = PPOS.PERSON_ID
	AND PAPF.PERSON_NUMBER LIKE 'TEST%'
	AND SYSDATE BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE
	AND HIKM.OBJECT_NAME = 'PeriodOfService'
	AND PAAM.ASSIGNMENT_TYPE NOT LIKE '%T'
	--AND PPOS.REHIRE_RECOMMENDATION LIKE 'Y'
	AND PAAM.EFFECTIVE_START_DATE = (SELECT MAX(PAAM2.EFFECTIVE_START_DATE)
										FROM PER_ALL_ASSIGNMENTS_M PAAM2
										WHERE 1 = 1
											AND PAAM2.ASSIGNMENT_ID = PAAM.ASSIGNMENT_ID
											AND PAAM2.PERSON_ID = PAAM.PERSON_ID
											AND PAAM2.ASSIGNMENT_TYPE = PAAM.ASSIGNMENT_TYPE)
	AND PAAM.ASSIGNMENT_SEQUENCE = (SELECT MAX(PAAM2.ASSIGNMENT_SEQUENCE)
										FROM PER_ALL_ASSIGNMENTS_M PAAM2
										WHERE 1 = 1
											AND PAAM2.ASSIGNMENT_ID = PAAM.ASSIGNMENT_ID
											AND PAAM2.PERSON_ID = PAAM.PERSON_ID
											AND PAAM2.ASSIGNMENT_TYPE = PAAM.ASSIGNMENT_TYPE)
	AND PPOS.LAST_UPDATE_DATE = (SELECT MAX(PPOS2.LAST_UPDATE_DATE)
									FROM PER_PERIODS_OF_SERVICE PPOS2
									WHERE 1 = 1
										AND PPOS.PERSON_ID = PPOS2.PERSON_ID)
	AND PPOS.DATE_START = (SELECT MAX(PPOS2.DATE_START)
									FROM PER_PERIODS_OF_SERVICE PPOS2
									WHERE 1 = 1
									AND PPOS.PERSON_ID = PPOS2.PERSON_ID)
	AND NOT EXISTS (SELECT PPOS2.DATE_START
					FROM PER_PERIODS_OF_SERVICE PPOS2
					WHERE 1 = 1
						AND PPOS.DATE_START > PPOS.DATE_START
						AND PPOS2.PERSON_ID = PPOS.PERSON_ID)
ORDER BY 1
