SELECT DISTINCT PAPF.PERSON_NUMBER "PersonNumber"
	, TO_CHAR(PAPF.EFFECTIVE_START_DATE, 'YYYY/MM/DD') "EffectiveStartDate"
	, TO_CHAR(PAPF.EFFECTIVE_END_DATE, 'YYYY/MM/DD') "EffectiveEndDate"
	, TO_CHAR(PAPF.START_DATE, 'YYYY/MM/DD') "StartDate"
	, TO_CHAR(PP.DATE_OF_BIRTH, 'YYYY/MM/DD') "DateOfBirth"
	, PP.COUNTRY_OF_BIRTH "CountryOfBirth"
	, PAAM.ACTION_CODE "ActionCode"
	, HIKM.SOURCE_SYSTEM_ID "SourceSystemId"
	, HIKM.SOURCE_SYSTEM_OWNER "SourceSystemOwner"
FROM PER_ALL_PEOPLE_F PAPF
	, PER_PERSONS PP
	, PER_ALL_ASSIGNMENTS_M PAAM
	, HRC_INTEGRATION_KEY_MAP HIKM
WHERE 1 = 1
	AND PAPF.PERSON_ID = PP.PERSON_ID
	AND PAPF.PERSON_ID = PAAM.PERSON_ID
	AND HIKM.SURROGATE_ID = PAPF.PERSON_ID
	AND PAPF.PERSON_NUMBER LIKE 'TEST%'
	AND PAAM.ACTION_CODE = 'HIRE'
ORDER BY 1
